### ISSUE TITLE
Deploys occasionally fail with RestClient::BadRequest

### ISSUE THREAD

**Issue by tessereth** [AusDTO/qa-fire#55]

**Comment by tessereth** [comment]
```
Wed Sep 21 2016 12:08:16 GMT+1000 (AEST) [APP] OUT 2016-09-21T02:08:16.302Z 19 TID-gqv9p5ngo ServerLaunchJob JID-b4ae23f73fd3fa66757f947d INFO: start
Wed Sep 21 2016 12:08:16 GMT+1000 (AEST) [APP] OUT D, [2016-09-21T02:08:16.304376 #19] DEBUG -- : [1m[36mDeploy Load (0.4ms)[0m [1m[34mSELECT "deploys".* FROM "deploys" WHERE "deploys"."id" = $1 LIMIT $2[0m [["id", 9], ["LIMIT", 1]]
Wed Sep 21 2016 12:08:16 GMT+1000 (AEST) [APP] OUT I, [2016-09-21T02:08:16.305216 #19] INFO -- : [ActiveJob] [ServerLaunchJob] [3e231549-1024-4838-875a-ef751dd15106] Performing ServerLaunchJob from Sidekiq(default) with arguments: #<GlobalID:0x0055ef5ecaa258 @uri=#<URI::GID gid://qa-fire/Deploy/9>>
Wed Sep 21 2016 12:08:16 GMT+1000 (AEST) [APP] OUT D, [2016-09-21T02:08:16.306423 #19] DEBUG -- : [ActiveJob] [ServerLaunchJob] [3e231549-1024-4838-875a-ef751dd15106] [1m[36mProject Load (0.3ms)[0m [1m[34mSELECT "projects".* FROM "projects" WHERE "projects"."id" = $1 LIMIT $2[0m [["id", 1], ["LIMIT", 1]]
Wed Sep 21 2016 12:08:16 GMT+1000 (AEST) [APP] OUT I, [2016-09-21T02:08:16.306840 #19] INFO -- : [ActiveJob] [ServerLaunchJob] [3e231549-1024-4838-875a-ef751dd15106] Executing git clone https://github.com/tessereth/helloworld-html.git /home/vcap/tmp/tmp/manual-helloworld-html --branch master --depth 1 --single-branch
Wed Sep 21 2016 12:08:16 GMT+1000 (AEST) [APP] OUT cloning git and creating application archive
Wed Sep 21 2016 12:08:18 GMT+1000 (AEST) [APP] OUT Deflating /home/vcap/tmp/tmp/manual-helloworld-html/index.html
Wed Sep 21 2016 12:08:18 GMT+1000 (AEST) [APP] OUT Deflating /home/vcap/tmp/tmp/manual-helloworld-html/manifest.yml
Wed Sep 21 2016 12:08:18 GMT+1000 (AEST) [APP] OUT Deflating /home/vcap/tmp/tmp/manual-helloworld-html/Staticfile
Wed Sep 21 2016 12:08:18 GMT+1000 (AEST) [APP] OUT Launching manual-helloworld-html
Wed Sep 21 2016 12:08:19 GMT+1000 (AEST) [APP] OUT logged in to cf in space qafire (289f32b7-b566-4677-8080-35dfc862bf7d)
Wed Sep 21 2016 12:08:19 GMT+1000 (AEST) [APP] OUT created new app a8c7409e-3fe0-4dc1-b656-737a2f00e7b4
Wed Sep 21 2016 12:08:19 GMT+1000 (AEST) [APP] OUT found existing route 96e1889c-f036-4913-9a08-1540d6dafe28
Wed Sep 21 2016 12:08:19 GMT+1000 (AEST) [APP] OUT waiting for push to complete
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT No services
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT push complete for manual-helloworld-html
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT I, [2016-09-21T02:08:20.538418 #19] INFO -- : [ActiveJob] [ServerLaunchJob] [3e231549-1024-4838-875a-ef751dd15106] Performed ServerLaunchJob from Sidekiq(default) in 4233.05ms
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT 2016-09-21T02:08:20.539Z 19 TID-gqv9p5ngo ServerLaunchJob JID-b4ae23f73fd3fa66757f947d INFO: fail: 4.237 sec
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT 2016-09-21T02:08:20.539Z 19 TID-gqv9p5ngo WARN: {"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"ServerLaunchJob","queue":"default","args":[{"job_class":"ServerLaunchJob","job_id":"3e231549-1024-4838-875a-ef751dd15106","queue_name":"default","priority":null,"arguments":[{"_aj_globalid":"gid://qa-fire/Deploy/9"}],"locale":"en"}],"retry":3,"jid":"b4ae23f73fd3fa66757f947d","created_at":1474423696.3038735,"enqueued_at":1474423696.3039758,"error_message":"400 Bad Request","error_class":"RestClient::BadRequest","failed_at":1474423700.5388258,"retry_count":0}
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT 2016-09-21T02:08:20.539Z 19 TID-gqv9p5ngo WARN: RestClient::BadRequest: 400 Bad Request
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT 2016-09-21T02:08:20.539Z 19 TID-gqv9p5ngo WARN: /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.0/lib/restclient/abstract_response.rb:223:in `exception_with_response'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.0/lib/restclient/abstract_response.rb:103:in `return!'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.0/lib/restclient/request.rb:860:in `process_result'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.0/lib/restclient/request.rb:776:in `block in transmit'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:853:in `start'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.0/lib/restclient/request.rb:766:in `transmit'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.0/lib/restclient/request.rb:215:in `execute'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.0/lib/restclient/request.rb:52:in `execute'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/rest-client-2.0.0/lib/restclient.rb:79:in `put'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/app/services/cloud_foundry.rb:184:in `start_app'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/app/services/server.rb:34:in `launch!'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/app/jobs/server_launch_job.rb:5:in `perform'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.0.1/lib/active_job/execution.rb:34:in `block in perform_now'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:126:in `call'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.0.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:447:in `block in around'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.0.1/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `block in instrument'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `instrument'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `block in tagged'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `tagged'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.0.1/lib/active_job/logging.rb:44:in `tag_logger'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.0.1/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.0.1/lib/active_job/logging.rb:44:in `block in tag_logger'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:26:in `tagged'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.0.1/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:447:in `block in around'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.0.1/lib/active_job/execution.rb:33:in `perform_now'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.0.1/lib/active_job/execution.rb:22:in `block in execute'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:126:in `call'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/reloader.rb:67:in `wrap'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:447:in `block in around'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_execute_callbacks'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.0.1/lib/active_job/queue_adapters/sidekiq_adapter.rb:40:in `perform'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/logging.rb:32:in `with_context'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_perform_callbacks'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.0.1/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/execution_wrapper.rb:76:in `wrap'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/reloader.rb:68:in `block in wrap'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/execution_wrapper.rb:76:in `wrap'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.0.1/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.0.1/lib/active_job/execution.rb:20:in `execute'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:152:in `execute_job'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:134:in `block (2 levels) in process'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/logging.rb:7:in `call'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:133:in `invoke'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:129:in `block in process'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/util.rb:17:in `watchdog'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:168:in `stats'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:128:in `process'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:80:in `process_one'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:68:in `run'
Wed Sep 21 2016 12:08:20 GMT+1000 (AEST) [APP] OUT /home/vcap/app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by tessereth** [comment]
This appears to be fixed by waiting for the correct state change on the file upload job (cb142ce6ddd0ceefa0985057c164399e4f53a718). If the error continues to happen, please reopen or create a new issue with a new stack trace.

**Comment by bjgordon** [comment]
I haven't had it happen since, so looks good!
